[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# git

[[plugins]]
repo = 'tpope/vim-fugitive'

# toml

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# julia

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_ft = ['julia']

# ruby

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'mrkn/vim-cruby'

# terraform

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform', 'javascript']

# wakatime

[[plugins]]
repo = 'wakatime/vim-wakatime'

# etc.

[[plugins]]
repo = 'tpope/vim-surround'
