
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# deoplete

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# git

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# toml

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# julia

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_ft = ['julia']

# ruby

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'mrkn/vim-cruby'

# terraform

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform', 'javascript']

# wakatime

[[plugins]]
repo = 'wakatime/vim-wakatime'

# mrkn256
[[plugins]]
repo = 'mrkn/mrkn256.vim'

# Solarized

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# Tomorrow

[[plugins]]
repo = 'chriskempson/tomorrow-theme'
rtp = 'vim'

# nerdtree

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd VimEnter * execute 'NERDTree'
'''

# etc.

[[plugins]]
repo = 'tpope/vim-surround'
